exams/urls.py
from django.urls import include, path
from . import views
from django.conf.urls import  url

#namespace used for urls to separate the urls of the different apps in case there is same urlname
app_name = 'exams'
urlpatterns = [
    #the function executed to list the exams and the name of the url in the htnl template
    path('', views.exams_list,name='examurl'),
    #we capture that variabl and name it pk with <> and send it to the function in the view
    path('<int:pk>/',views.take_exam,name='detailurlexam'),
    path('exams_crud/', views.exams_crud,name='examcrud'),
    path('exams_crud/add_exam/', views.ExamCreateView.as_view(), name="add_exam"),
    path('exams_crud/<int:pk>/question_add/', views.question_add, name='question_add'),
    path('exams_crud/<int:quiz_pk>/<int:pk>/', views.CreateOrderView.as_view(), name='question_change'),
    path('exams_crud/<int:pk>/', views.question_list, name='question_list'),
    path('exams_crud/<int:pk>/updatequest/', views.CreateOrderView.as_view(), name='question_upd'),
    path('exams_crud/newexam/', views.ExamCreateView.as_view(), name='addex'),







]

successpass/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import  include
from .api import router
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
 path('admin/', admin.site.urls),
 path('nested_admin/', include('nested_admin.urls')),
 path('api/v1/', include(router.urls)), #routers for the Restframework

 #path home and its view
 path('', views.home,name='homeurl'),
 #urls of exams app
 #and name space specification for the templates path to make links between the html pages (templates)
 path('exams/', include('exams.urls',namespace="exams")),
 #urls of candidates app
 #and name space specification for the templates path to make links between the html pages (templates)
 path('candidates/', include('candidates.urls',namespace="candidates")),

 path('accounts/', include('accounts.urls',namespace="accounts")),

 # path to admin adding apps for the oautho2
 path("o/", include('oauth2_provider.urls', namespace='oauth2_provider')),
 # Authentication user resframework
 path('register/', views.register),
 path('token/', views.token),
 path('token/refresh/', views.refresh_token),
 path('token/revoke/', views.revoke_token),

]

urlpatterns += staticfiles_urlpatterns()

exams/forms.py
from django import forms
from .models import Exam, Questions, Options, Candidate,CandidateResponse,TakenExam
from django.forms.models import inlineformset_factory
from django.forms.utils import ValidationError
from django.forms.models import BaseInlineFormSet
from django.forms.models import inlineformset_factory
from . import models


class ExamForm(forms.ModelForm):
    class Meta:
        model =Exam
        fields='__all__'




class QuestionForm(forms.ModelForm):
    class Meta:
        model =Questions
        fields='__all__'


class OptionForm(forms.ModelForm):
    class Meta:
        model =Options
        fields='__all__'




class BaseAnswerInlineFormSet(forms.BaseInlineFormSet):
    def clean(self):
        super().clean()
        has_one_correct_answer = False
        for form in self.forms:
            if not form.cleaned_data.get('DELETE', False):
                if form.cleaned_data.get('is_correct', False):
                    has_one_correct_answer = True
                    break
        if not has_one_correct_answer:
            raise ValidationError('Mark at least one answer as correct.', code='no_correct_answer')

exams/views.py
from .models import Exam, Questions, Options, Candidate,CandidateResponse,TakenExam
from django.forms import inlineformset_factory
from django.shortcuts import render,get_object_or_404,redirect
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.urls import reverse
from datetime import datetime
from . import forms


from extra_views import InlineFormSetFactory, CreateWithInlinesView,UpdateWithInlinesView



#python manage.py migrate --run-syncdb  if the django doesnt recognize created tables via the python migrate  cmd

def paginatedItems(request,items,numberItem):
    paginator=Paginator(items,numberItem)
    page = request.GET.get('page')
    posts=paginator.get_page(page)
    return (posts)

#show list of exams for a candidate
#this decorator will add more functionalities to my function in oder to protect it
@login_required(login_url='/accounts/login/')
def exams_list(request):
    candidate = get_object_or_404(Candidate, pk=request.user.id)

    candidate=Candidate.objects.get(pk=request.user.id)
    exams=candidate.exams.all()
        #order the items!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    return render(request,'exams/exams_list.html',{'items': exams})


@login_required(login_url='/accounts/login/')
def take_exam(request, pk):
    #get list of exams
    #if fisrt time entering the quiz
    exam = get_object_or_404(Exam, pk=pk)
    #get id of logged candidate
    candidate = request.user.candidate
    #order the items!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    unanswered_questions = candidate.get_unanswered_questions(exam)
    posts=paginatedItems(request,unanswered_questions,2)

    if TakenExam.objects.filter(candidate=candidate,exam=exam,date_begin__isnull=True):
        TakenExam.objects.filter(candidate=candidate,exam=exam).update(date_begin=datetime.now())

    #for http://127.0.0.1:8080/exams/1
    if  request.method == 'GET':
        if candidate.exams.filter(pk=pk).exists():
            return render(request, 'exams/exams_detail.html', { 'exam': exam ,'items':posts})

    #if clicked on submit
    if  request.method == 'POST':
        question = get_object_or_404(Questions, pk=request.POST.get('question_id'))
        some_var = request.POST.getlist('choice')
        if len(some_var)> 0:
            selected_choice = question.options_set.filter(pk__in=some_var)

            answers_list = list(selected_choice)
            for item in answers_list:
                foo = CandidateResponse.objects.create(question=question,chosen_option=item,candidate=candidate)
                foo.save()
                #update this table TakenExam score and date of started and end of exam!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


            if candidate.get_unanswered_questions(exam).exists():
                next = request.POST.get('next')
                messages.success(request, ('Answer saved'))
                return redirect(next)
            else:
                candidate.calculate_score(exam)


                return redirect('exams:examurl')


        else:
            next = request.POST.get('next')
            messages.error(request, ('No option chosen!'))
            return redirect(next)

    return render(request, 'exams/exams_detail.html', {
        'exam': exam,
        'items':posts}
    )



def exams_crud(request):
    exams=Exam.objects.all()
    return render(request,'exams/exams_crud.html',{'items':exams})


def exam_add(request):
    if request.method == 'POST':
        form = forms.ExamForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('exams:examcrud')
    else:
        form = forms.ExamForm()

    return render(request, 'exams/exam_add.html', {
                  'form': form})


def question_add(request, pk):
    quiz = get_object_or_404(Exam, pk=pk)
    if request.method == 'POST':
        form = forms.QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.exam = quiz
            question.save()
            messages.success(request, 'You may now add answers/options to the question.')
            return redirect('exams:examcrud')
    else:
        form = forms.QuestionForm()

    return render(request, 'exams/question_add_form.html', {'quiz': quiz, 'form': form})

# exam questions and options are nested
# first user create an exam
#then he ll add a question to that exam
# after adding a question he can change it to add options with function below that uses inlineformset_factory to link options to the question
#needs pk of exam and pk of qurstion
#{"username": "useqwee", "password": "1234abcd", "firstName": "qweqweabcd", "lastName": "eqwqweqabcd", "phoneNumber": "112312313", "email": "qwqweeq@gmail.com"}

def question_change(request, quiz_pk, question_pk):
    quiz = get_object_or_404(Exam, pk=quiz_pk)
    question = get_object_or_404(Questions, pk=question_pk, exam=quiz_pk)
    AnswerFormSet = inlineformset_factory(
        Questions,  # parent model
        Options,  # base model
        formset=forms.BaseAnswerInlineFormSet, #rewrite clean method to check if he chosed at least one correct answer
        fields=('body', 'image','is_correct',),
        min_num=2,
        validate_min=True,
        extra=10,
        validate_max=True
    )
    if request.method == 'POST':
        form = forms.QuestionForm(request.POST, instance=question)#post here is to get the data and associate it with the instance to commit changes to it
        formset = AnswerFormSet(request.POST, instance=question)
        if form.is_valid() and formset.is_valid():
            #always use atomic transaction in case saving two different objects related by ForeignKey
            with transaction.atomic():
                form.save()
                formset.save()
            messages.success(request, 'Question and answers saved with success!')
            return redirect(reverse('exams:question_list', kwargs={"pk": quiz_pk}))
    else:
        form = forms.QuestionForm(instance=question)#in update forms we must send the instance back
        formset = AnswerFormSet(instance=question)

    return render(request, 'exams/question_change_form.html', {
        'quiz': quiz,
        'question': question,
        'form': form,
        'formset': formset
    })

def question_list(request, pk):
    questions=Questions.objects.filter(exam=pk)
    return render(request,'exams/questions_list.html',{'items': questions,'pk':pk})


#case 3 nested i can start creating exams and questions
#then if selected question create updatequestioninline and inlineformsetfactory of options
#then of option has ForeignKey make list of options of question then when clicked on option possibility of update it and adding the nested form
############################################################################################
class QuestionInline(InlineFormSetFactory):
    model = Questions
    fields = '__all__'

class ExamCreateView(CreateWithInlinesView):
    model = Exam
    inlines = [QuestionInline,]
    fields = '__all__'
    template_name = 'exams/crt.html'
    success_url = '/'
    factory_kwargs = {'extra': 0}


class OptionsInline(InlineFormSetFactory):
    model = Options
    fields = '__all__'

class CreateOrderView(UpdateWithInlinesView):
    model = Questions
    inlines = [OptionsInline,]
    fields = '__all__'
    template_name = 'exams/updatequest.html'
    success_url = '/'
    factory_kwargs = {'extra': 0}



from django.views.generic import TemplateView, ListView, CreateView

QuestionsInlineFormSet = inlineformset_factory(Exam, Questions,fields='__all__', extra=1, can_delete=False)
OptionsInlineFormSet = inlineformset_factory(Questions, Options,fields='__all__', extra=1, can_delete=False)


class ExamCreateView(CreateView):
    model = Exam
    fields='__all__'
    template_name = 'exams/tem.html'
    factory_kwargs = {'extra': 0}
    success_url = '/'

    def form_valid(self, form):
        result = super(ExamCreateView, self).form_valid(form)

        questions_formset = QuestionsInlineFormSet(form.data, instance=self.object, prefix='questions_formset')
        if questions_formset.is_valid():
            questions = questions_formset.save()

        questions_count = 0
        for question in questions:
            options_formset = OptionsInlineFormSet(form.data, instance=question, prefix='options_formset_%s' % questions_count)
            if options_formset.is_valid():
                options_formset.save()
            questions_count += 1

        return result

    def get_context_data(self, **kwargs):
        context = super(ExamCreateView, self).get_context_data(**kwargs)
        context['authors_formset'] = QuestionsInlineFormSet(prefix='questions_formset')
        context['books_formset'] = OptionsInlineFormSet(prefix='options_formset_0')
        return context

exams/templates/exams/crt.html
{% extends 'base_layout.html' %}

{% load static %}

{% block content%}

<form method="post">

  {{ form }}
  {% csrf_token %}

  {% for formset in inlines %}
  {{ formset.management_form }}
      {% for inline_form in formset %}
  <div class='table'>
  <table  class='no_error'>
          {{ inline_form }}
  </table>

</div>
{% endfor %}
{% endfor %}
  <input type="submit" value="Submit" />
  <input type="button" value="Add More" id="add_more">

</form>
{% endblock %}

{% block js %}

<script>
    $('#add_more').click(function() {
        cloneMore('div.table:last', 'questions_set');
    });
    function cloneMore(selector, type) {
    var newElement = $(selector).clone(true);
    var total = $('#id_' + type + '-TOTAL_FORMS').val();
    newElement.find(':input').each(function() {
        var name = $(this).attr('name').replace('-' + (total-1) + '-','-' + total + '-');
        var id = 'id_' + name;

        if ($(this).attr('type') != 'hidden') {
            $(this).val('');
        }
        $(this).attr({'name': name, 'id': id}).removeAttr('checked');
    });
    newElement.find('label').each(function() {
        var newFor = $(this).attr('for').replace('-' + (total-1) + '-','-' + total + '-');
        $(this).attr('for', newFor);
    });
    total++;
    $('#id_' + type + '-TOTAL_FORMS').val(total);
    $(selector).after(newElement);
}
</script>

{% endblock %}

exams/templates/exams/exams_crud.html
{% extends 'base_layout.html' %}

{% load static %}



{% block css %}
<!-- DataTables https://cdn.datatables.net/ -->
  <link rel="stylesheet" type="text/css" href="{% static 'datatablecss/bootstrap.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'datatablecss/dataTables.bootstrap4.min.css' %}">
  {% endblock %}


{% block content%}
<a href="{% url 'exams:add_exam' %}"><button>Add exam</button></a>

<div class="exams">
<h1>Exams</h1>

<table class="table table-bordered" id="tb_exams">
  <thead>
    <tr>
      <th>title</th>
      <th>percentage</th>
      <th>Operations</th>

    </tr>
  </thead>
  <body>
    {% for item in items %}
      <tr>
        <!-- namespace+name of url present in the .urls of the app-->
    <td>{{ item.title }}</td>
		<td><a href="{% url 'exams:question_list' item.id %}">List Questions</a></td>
    <td><a href="{% url 'exams:question_add' item.id %}"><button>Add questions</button></a></td>

      </tr>
    {% endfor %}
  </body>
</table>

</div>

{% endblock %}


{% block js %}
<!-- DataTables https://cdn.datatables.net/ -->
<script type="text/javascript" src="{% static 'datatablecss/jquery-3.3.1.js' %}"></script>
<script type="text/javascript" src="{% static 'datatablecss/jquery.dataTables.min.js' %} "></script>
<script type="text/javascript" src="{% static 'datatablecss/dataTables.bootstrap4.min.js' %}  "></script>
<script >
$(document).ready( function () {
  $('#tb_exams').DataTable();
} );
</script>
{% endblock %}

exams/templates/exams/exams_detail.html
{% extends 'base_layout.html' %}

{% load bootstrap_pagination %}

{%block content%}




<div class="exam-detail" >
  {% if messages %}
      {% for message in messages %}
          <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}" role="alert">{{ message }}  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
</div>
      {% endfor %}
  {% endif %}


  <h2>{{exam.title}}</h2>
  {% for question in items %}
  <p>{{question.title}}</p>
  <form action="{% url 'exams:detailurlexam' exam.id  %}" method="post">
    {% csrf_token %}
    {% for choice in question.options_of_question %}

    <input type="hidden" name="question_id" value="{{question.id}}">

    <input type="{{question.contentType}}" name="choice" id="choice{{forloop.counter}}" value="{{choice.id}}">
    <label for="choice{{forloop.counter}}">{{ choice.body }}</label><br>
    {% endfor %}
    <input type="submit" value="Submit">
    <input type="hidden" name="next" value="{{ request.get_full_path }}">

    </form>
  {%endfor%}
  <div class="pagination">
  {% if items.paginator.num_pages > 1 %}
      <!-- start -->
      {% include 'pagination.html' with items=items %}
      <!-- end -->
  {% endif %}
  </div>
  </div>

{%block js%}
<script type="text/javascript">
  window.setTimeout(function() {
    $(".alert").fadeTo(500, 0).slideUp(500, function(){
        $(this).remove();
    });
}, 2000);
</script>
{%endblock%}

{%endblock%}

exams/templates/exams/exams_list.html
{% extends 'base_layout.html' %}

{% load static %}



{% block css %}
<!-- DataTables https://cdn.datatables.net/ -->
  <link rel="stylesheet" type="text/css" href="{% static 'datatablecss/bootstrap.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'datatablecss/dataTables.bootstrap4.min.css' %}">
  {% endblock %}


{% block content%}
<div class="exams">
<h1>Exams</h1>
<table class="table table-bordered" id="tb_exams">
  <thead>
    <tr>
      <th>title</th>
      <th>duration</th>
      <th>percentage</th>
    </tr>
  </thead>
  <body>
    {% for item in items %}
      <tr>
        <!-- namespace+name of url present in the .urls of the app-->
        <td><a href="{% url 'exams:detailurlexam' item.id %}">{{ item.title }}</a></td>
        <td>{{ item.duration}}</td>
		<td>{{ item.percentage }}</td>
      </tr>
    {% endfor %}
  </body>
</table>

</div>

{% endblock %}


{% block js %}
<!-- DataTables https://cdn.datatables.net/ -->
<script type="text/javascript" src="{% static 'datatablecss/jquery-3.3.1.js' %}"></script>
<script type="text/javascript" src="{% static 'datatablecss/jquery.dataTables.min.js' %} "></script>
<script type="text/javascript" src="{% static 'datatablecss/dataTables.bootstrap4.min.js' %}  "></script>
<script >
$(document).ready( function () {
  $('#tb_exams').DataTable();
} );
</script>
{% endblock %}

exams/templates/exams/question_add_form.html
{% extends 'base_layout.html' %}

{% load static %}


{% load crispy_forms_tags %}

{% block content %}
  <h2 class="mb-3">Add a new question</h2>
  <p class="lead">Add first the text of the question. In the next step you will be able to add the possible answers.</p>
  <form method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success">Save</button>
  </form>
{% endblock %}

exams/templates/exams/question_change_form.html
{% extends 'base_layout.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
  <h2 class="mb-3">{{ question.description }}</h2>
  <form method="post" novalidate>
    {% csrf_token %}
    {{ formset.management_form }}
    {{ form|crispy }}
    <div class="card mb-3{% if formset.errors %} border-danger{% endif %}">
      <div class="card-header">
        <div class="row">
          <div class="col-8">
            <strong>Answers</strong>
          </div>
          <div class="col-2">
            <strong>Correct?</strong>
          </div>
          <div class="col-2">
            <strong>Delete?</strong>
          </div>
        </div>
      </div>
      <!--  write the error raised by the clean method -->
      <!-- write error raised by min 2 options-->
      <!-- write error raised by max 10 options-->
      <!-- if the instance option exists in the bd and the user entred a different text for that option here we target blank option-->

      {% for error in formset.non_form_errors %}
        <div class="card-body bg-danger border-danger text-white py-2">{{ error }}</div>
      {% endfor %}

      <div class="list-group list-group-flush list-group-formset">
        {% for form in formset %}
          <div class="list-group-item">
            <div class="row">
              <div class="col-8">
                <!--hidden fields with values that are simply returned to the server when the completed form is submitted.
                -->
                {% for hidden in form.hidden_fields %}{{ hidden }}{% endfor %}
                <!--visible fields that the user fills in, or-->

                {{ form.body|as_crispy_field }}
                {{ form.image|as_crispy_field }}
<!-- if the instance option exists in the bd and the user entred blank text for that option rise error !!!!!!!!!!!!!!11-->
                {% if form.instance.pk and form.body == "" %}<p class="mb-0 mt-1"><small class="text-muted font-italic"><strong>Old answer:</strong> {{ form.instance.body }}</small></p>{% endif %}
              </div>
              <div class="col-2">
                {{ form.is_correct }}
              </div>
              <div class="col-2">
              <!--  if the option exists in the database output delete field to delete it from database-->
                {% if form.instance.pk %}
                  {{ form.DELETE }}
                {% endif %}
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
    <p>
      <small class="form-text text-muted">Your question may have at least <strong>2</strong> answers and maximum <strong>10</strong> answers. Select at least one correct answer.</small>
    </p>
    <button type="submit" class="btn btn-success">Save changes</button>
  </form>
{% endblock %}

exams/templates/exams/questions_list.html
{% extends 'base_layout.html' %}

{% load static %}



{% block css %}
<!-- DataTables https://cdn.datatables.net/ -->
  <link rel="stylesheet" type="text/css" href="{% static 'datatablecss/bootstrap.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'datatablecss/dataTables.bootstrap4.min.css' %}">
  {% endblock %}


{% block content%}
<a href="{% url 'exams:add_exam' %}"><button>Add exam</button></a>

<div class="exams">
<h1>Exams</h1>

<table class="table table-bordered" id="tb_exams">
  <thead>
    <tr>
      <th>title</th>
      <th>percentage</th>
      <th>Operations</th>

    </tr>
  </thead>
  <body>
    {% for item in items %}
      <tr>
        <!-- namespace+name of url present in the .urls of the app-->
    <td>{{ item.title }}</td>
		<td><a href="{% url 'exams:question_change' pk item.id %}">Change Question</a></td>

      </tr>
    {% endfor %}
  </body>
</table>

</div>

{% endblock %}


{% block js %}
<!-- DataTables https://cdn.datatables.net/ -->
<script type="text/javascript" src="{% static 'datatablecss/jquery-3.3.1.js' %}"></script>
<script type="text/javascript" src="{% static 'datatablecss/jquery.dataTables.min.js' %} "></script>
<script type="text/javascript" src="{% static 'datatablecss/dataTables.bootstrap4.min.js' %}  "></script>
<script >
$(document).ready( function () {
  $('#tb_exams').DataTable();
} );
</script>
{% endblock %}

exams/templates/exams/tem.html
<script type="text/javascript" src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script type="text/javascript">
    $(function () {
        $('form').delegate('.btn_add_book', 'click', function () {
            var $this = $(this)
            var author_ptr = $this.attr('id').split('-')[1]
            var $total_author_books = $(':input[name=books_formset_' + author_ptr + '-TOTAL_FORMS]');
            var author_book_form_count = parseInt($total_author_books.val())
            $total_author_books.val(author_book_form_count + 1)

            var $new_book_form = $('<fieldset class="author_book_form">' +
                '<legend>Book</legend>' +
                '<p>' +
                '<label for="id_books_formset_' + author_ptr + '-' + author_book_form_count + '-name">Name:</label>' +
                '<input id="id_books_formset_' + author_ptr + '-' + author_book_form_count + '-name" maxlength="256" name="books_formset_' + author_ptr + '-' + author_book_form_count + '-name" type="text" />' +
                '<input id="id_books_formset_' + author_ptr + '-' + author_book_form_count + '-author" name="books_formset_' + author_ptr + '-' + author_book_form_count + '-author" type="hidden" />' +
                '<input id="id_books_formset_' + author_ptr + '-' + author_book_form_count + '-id" name="books_formset_' + author_ptr + '-' + author_book_form_count + '-id" type="hidden" />' +
                '</p>' +
                '</fieldset>'
            )

            $this.parents('.author_form').find('.author_books').prepend($new_book_form)
        })

        $('form').delegate('#btn_add_author', 'click', function () {
            var $total_authors = $(':input[name=authors_formset-TOTAL_FORMS]');
            author_form_count = parseInt($total_authors.val())
            $total_authors.val(author_form_count + 1)

            book_form = '<fieldset class="author_book_form">' +
                '<legend>Book</legend>' +
                '<p>' +
                '<label for="id_books_formset_' + author_form_count + '-0-name">Name:</label>' +
                '<input id="id_books_formset_' + author_form_count + '-0-name" maxlength="256" name="books_formset_' + author_form_count + '-0-name" type="text" />' +
                '<input id="id_books_formset_' + author_form_count + '-0-author" name="books_formset_' + author_form_count + '-0-author" type="hidden" />' +
                '<input id="id_books_formset_' + author_form_count + '-0-id" name="books_formset_' + author_form_count + '-0-id" type="hidden" />' +
                '</p>' +
                '</fieldset>';

            $new_author_form = $(
                '<fieldset class="author_form">' +
                '<legend>Author</legend>' +
                '<p>' +
                '<label for="id_authors_formset-' + author_form_count + '-name">Name:</label>' +
                '<input id="id_authors_formset-' + author_form_count + '-name" maxlength="256" name="authors_formset-' + author_form_count + '-name" type="text" />' +
                '<input id="id_authors_formset-' + author_form_count + '-publisher" name="authors_formset-' + author_form_count + '-publisher" type="hidden" />' +
                '<input id="id_authors_formset-' + author_form_count + '-id" name="authors_formset-' + author_form_count + '-id" type="hidden" />' +
                '</p>' +
                '<p><input type="button" value="Add Book" class="btn_add_book" id="author-' + author_form_count + '"/></p>' +
                '<div class="author_books">' +
                '<input id="id_books_formset_' + author_form_count + '-TOTAL_FORMS" name="books_formset_' + author_form_count + '-TOTAL_FORMS" type="hidden" value="1" />' +
                '<input id="id_books_formset_' + author_form_count + '-INITIAL_FORMS" name="books_formset_' + author_form_count + '-INITIAL_FORMS" type="hidden" value="0" />' +
                '<input id="id_books_formset_' + author_form_count + '-MAX_NUM_FORMS" name="books_formset_' + author_form_count + '-MAX_NUM_FORMS" type="hidden" value="1000" />' +
                book_form +
                '</div >' +
                '</fieldset >'
            )

            $('#authors').prepend($new_author_form)
        })
    })
</script>
<h1>Add Publisher</h1>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}

    <p><input type="button" id="btn_add_author" value="Add another author"/></p>

    <div id="authors">
        {{ authors_formset.management_form }}
        {% for form in authors_formset %}
            <fieldset class="author_form">
                <legend>Author</legend>
                {{ form.as_p }}
                <p><input type="button" value="Add Book" class="btn_add_book" id="author-{{ forloop.counter0 }}"/></p>

                <div class="author_books">
                    {{ books_formset.management_form }}
                    {% for form in books_formset %}
                        <fieldset class="author_book_form">
                            <legend>Book</legend>
                            {{ form.as_p }}
                        </fieldset>
                    {% endfor %}
                </div>
            </fieldset>
        {% endfor %}
    </div>
    <p><input type="submit" value="Save"></p>
</form>

exams/templates/exams/test.html
{% extends 'base_layout.html' %}

{% load static %}


{% load crispy_forms_tags %}

{% block content %}
  <h2 class="mb-3">Add a new Exam</h2>
  <form method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success">Save</button>
  </form>
{% endblock %}

exams/templates/exams/updatequest.html
{% extends 'base_layout.html' %}

{% load static %}

{% block content%}
<form method="post"  enctype='multipart/form-data'>

  {{ form }}
  {% csrf_token %}

  {% for formset in inlines %}
  {{ formset.management_form }}
      {% for inline_form in formset %}
  <div class='table'>
  <table  class='no_error'>
          {{ inline_form }}
  </table>

</div>
{% endfor %}
{% endfor %}
  <input type="submit" value="Submit" />
  <input type="button" value="Add More" id="add_more">

</form>

{% endblock %}



{% block js %}
<!--did remove checked and replaced it with value inorder to take it and save it-->
<script>
    $('#add_more').click(function() {
        cloneMore('div.table:last', 'options_set');
    });
    function cloneMore(selector, type) {
    var newElement = $(selector).clone(true);
    var total = $('#id_' + type + '-TOTAL_FORMS').val();
    newElement.find(':input').each(function() {
        var name = $(this).attr('name').replace('-' + (total-1) + '-','-' + total + '-');
        var id = 'id_' + name;

        if ($(this).attr('type') != 'hidden') {
            $(this).val('');
        }
        $(this).attr({'name': name, 'id': id}).removeAttr('value');
    });
    newElement.find('label').each(function() {
        var newFor = $(this).attr('for').replace('-' + (total-1) + '-','-' + total + '-');
        $(this).attr('for', newFor);
    });
    total++;
    $('#id_' + type + '-TOTAL_FORMS').val(total);
    $(selector).after(newElement);
}
</script>

{% endblock %}