accounts/urls.py
from django.conf.urls import  url
from . import views
#namespace used for urls to separate the urls of the different apps in case there is same urlname
app_name = 'accounts'
urlpatterns = [
    #the function executed to list the exams and the name of the url in the htnl template
    url(r'^signup/$', views.signup_view,name='signup'),
    url(r'^login/$', views.login_view,name='login'),
    url(r'^logout/$', views.logout_view,name='logout'),

]

candidates/urls.py
from django.urls import include, path
from . import views

#add app name for namespace to work
app_name = 'candidates'
urlpatterns = [
    #path to the folder containing the home view and the eexecuted function
    path('', views.candidates_list,name="candidateurl"), 

]

exams/urls.py
from django.urls import include, path
from . import views
from django.conf.urls import  url

#namespace used for urls to separate the urls of the different apps in case there is same urlname
app_name = 'exams'
urlpatterns = [
    #the function executed to list the exams and the name of the url in the htnl template
    path('', views.exams_list,name='examurl'),
    #we capture that variabl and name it pk with <> and send it to the function in the view
    path('<int:pk>/',views.take_exam,name='detailurlexam'),
    path('exams_crud/', views.exams_crud,name='examcrud'),
    path('exams_crud/add_exam/', views.ExamCreateView.as_view(), name="add_exam"),
    path('exams_crud/<int:pk>/question_add/', views.question_add, name='question_add'),
    path('exams_crud/<int:quiz_pk>/<int:pk>/', views.CreateOrderView.as_view(), name='question_change'),
    path('exams_crud/<int:pk>/', views.question_list, name='question_list'),
    path('exams_crud/<int:pk>/updatequest/', views.CreateOrderView.as_view(), name='question_upd'),
    path('exams_crud/newexam/', views.ExamCreateView.as_view(), name='addex'),







]

successpass/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import  include
from .api import router
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
 path('admin/', admin.site.urls),
 path('nested_admin/', include('nested_admin.urls')),
 path('api/v1/', include(router.urls)), #routers for the Restframework

 #path home and its view
 path('', views.home,name='homeurl'),
 #urls of exams app
 #and name space specification for the templates path to make links between the html pages (templates)
 path('exams/', include('exams.urls',namespace="exams")),
 #urls of candidates app
 #and name space specification for the templates path to make links between the html pages (templates)
 path('candidates/', include('candidates.urls',namespace="candidates")),

 path('accounts/', include('accounts.urls',namespace="accounts")),

 # path to admin adding apps for the oautho2
 path("o/", include('oauth2_provider.urls', namespace='oauth2_provider')),
 # Authentication user resframework
 path('register/', views.register),
 path('token/', views.token),
 path('token/refresh/', views.refresh_token),
 path('token/revoke/', views.revoke_token),

]

urlpatterns += staticfiles_urlpatterns()

templates/base_layout.html
{% load static %}

{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}


<!DOCTYPE html>

<html>
    <head>

        <meta charset="utf-8">
        <link rel="stylesheet" href="{% static 'styles.css' %}">
        <meta charset="UTF-8">
        <!-- pagination-->
        <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
        <link rel="stylesheet" href="{% static 'pagination/pagination.css' %}">
        <!-- end pagination-->


    {% block css %}
    {% endblock %}

  <title>Successpass</title>
    </head>
    <body>
      <header class="wrapper">
        <nav>
          <ul>
            {%if user.is_authenticated%}
            <li>
            <!--  when submitting it ll make a post request to the url we did link to the view in paths of the acc app-->
              <form class="logout-link" action="{% url 'accounts:logout'%}" method="post">
                <!-- when ever we make a post request alwas add this token-->
                {%csrf_token%}
                <button type="submit">Logout</button>
              </form>
            </li>
            <hr>

              <li><a href="{%url 'exams:examurl' %}">exams</a></li>
              <li><a href="{%url 'candidates:candidateurl' %}">candidates</a></li>

            {%else%}
            <li> <a href="{%url 'accounts:login'%}">Login</a> </li>
            <li> <a href="{%url 'accounts:signup'%}">Signup</a> </li>
            <hr>
            <!-- here show the exams for a candidate-->

            {%endif%}
          </ul>
        </nav>

      </header>
        <div class="wrapper">
            {% block content %}
            {% endblock %}
        </div>
        {% block js %}
        {% endblock %}
    </body>
</html>

templates/home.html
{% extends 'base_layout.html' %}

{% block content%}
        <h1>Welcome to the success pass test</h1>
            <div class="article">
              <p>
                If you already have an account, go ahead and <a href="{%url 'accounts:login' %}">log in</a>. If you are new, get started
                by creating an <a href="{%url 'accounts:signup' %}">account</a>.
              </p>
            </div>
{% endblock %}

templates/pagination.html
  {% if items.has_previous %}
  <a class="pagination-action" href="?page=1">
  <i class="fa fa-angle-double-left" aria-hidden="true"></i> </a>
  <a class="pagination-action" href="?page={{ items.previous_page_number }}">
  <i class="fa fa-angle-left" aria-hidden="true"></i>
  </a>
  {% endif %}

    {% for num in items.paginator.page_range %}
    {% if items.number == num %}
    <span class="pagination-number pagination-current">{{ num }}</span>
    {% elif num > items.number|add:'-3' and num < items.number|add:'3' %}
    <a class="pagination-number" href="?page={{ num }}">{{ num }}</a>
    {% endif %}
    {% endfor %}

    {% if items.has_next %}
    <a class="pagination-action" href="?page={{ items.next_page_number }}">
    <i class="fa fa-angle-right" aria-hidden="true"></i>
    </a>
    <a class="pagination-action" href="?page={{ items.paginator.num_pages }}">
    <i class="fa fa-angle-double-right" aria-hidden="true"></i>
    </a>
    {% endif %}